//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EElections
{
    using System;
    using System.Collections.Generic;
    
    public partial class CE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CE()
        {
            this.voteTables = new HashSet<VoteTable>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int sectorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoteTable> voteTables { get; set; }
        public virtual Sector sector { get; set; }
    }
}
