//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voteManager
{
    using System;
    
    public enum TypeUser : int
    {
        Admin = 0,
        Standard = 1,
        Sytem = 2,
        Guest = 3
    }
}
