//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoteManager
{
    using System;
    
    public enum TypeUser : int
    {
        Standard = 0,
        Admin = 1,
        SuperAdmin = 2
    }
}
