//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voteManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class voteAppEntities : DbContext
    {
        public voteAppEntities()
            : base("name=voteAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Region> Regions1 { get; set; }
        public virtual DbSet<sector> sectors { get; set; }
        public virtual DbSet<partido> partidos { get; set; }
        public virtual DbSet<CE> CEs { get; set; }
        public virtual DbSet<voteTable> voteTables { get; set; }
        public virtual DbSet<vote> votes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
