//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voteManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class voteTable
    {
        public int Id { get; set; }
        public int CEId { get; set; }
    
        public virtual CE CE { get; set; }
    }
}
