//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voteManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int Id { get; set; }
        public int idRegion { get; set; }
        public int idSector { get; set; }
        public int idCE { get; set; }
        public int idVoteTable { get; set; }
        public int idPartido { get; set; }
        public int provinceId { get; set; }
        public int voteData { get; set; }
    }
}
