//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSampleBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CEId { get; set; }
        public int TotalRegisted { get; set; }
        public int InvalidVotes { get; set; }
    
        public virtual CE CE { get; set; }
    }
}
